# Dockerfile.dev — Catalog Service
FROM node:20-alpine
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate --schema=src/db/prisma/schema.prisma

EXPOSE 3002

CMD ["sh", "-c", "npx prisma db push --schema=src/db/prisma/schema.prisma --accept-data-loss && npx tsx src/db/seed.ts && npm run dev"]
