FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate --schema=src/db/prisma/schema.prisma
EXPOSE 3004
CMD ["sh", "-c", "npx prisma db push --schema=src/db/prisma/schema.prisma --accept-data-loss && npm run dev"]
